version: '3'
services:
  mysql:
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=products"
      - "MYSQL_ROOT_USERNAME=root"
    image: mysql:5.7
    ports: 
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./initdata:/docker-entrypoint-initdb.d
  
  web:
    build: .
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
    ports: 
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
      
volumes:
  initdata:
